### ISSUE TITLE
external connection

### ISSUE THREAD

**Issue by Adarsh-achu** [dunstad/bedrock-bot#7]
can i do this with external server hosting.

**Comment by dunstad** [comment]
You mean run the bot on a different computer than the server? In theory
yes, but you'd have to write some more code yourself to make it happen.

**Comment by Adarsh-achu** [comment]
Oh I want to use this to aternos hosting can i do that?.

**Comment by dunstad** [comment]
I'm not familiar with their service, but based on a quick look I doubt it.
Sorry I can't help much!
